spring:
  datasource:
    url: jdbc:postgresql://db:5432/DB_USERS
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 100

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format-sql: true

  cache:
    type: redis

  data:
    redis:
      host: cache
      port: 6379

